openapi: 3.0.0
info:
  title: Webhook API
  version: 1.0.0
  description: API for webhook registration, verification, and management
paths:
  /webhooks:
    post:
      summary: Register a webhook
      description: Allows customers to register a webhook with configurations.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WebhookRegistration'
      responses:
        '200':
          description: Webhook registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookRegistrationResponse'
    get:
      summary: Get webhook data
      description: Retrieve webhook data based on webhook name or organization name.
      parameters:
        - name: webhookName
          in: query
          description: Webhook name
          required: false
          schema:
            type: string
        - name: orgName
          in: query
          description: Organization name
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Webhook data retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookDataResponse'
  /webhooks/{webhookId}/test:
    post:
      summary: Test the webhook
      description: Allows customers to test a registered webhook by echoing the message sent.
      parameters:
        - name: webhookId
          in: path
          description: Unique identifier of the registered webhook
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WebhookTestRequest'
      responses:
        '200':
          description: Webhook test successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookTestResponse'
  /webhooks/{webhookId}:
    delete:
      summary: Delete a webhook
      description: Delete a registered webhook. If associated with any subscription, it won't be deleted.
      parameters:
        - name: webhookId
          in: path
          description: Unique identifier of the registered webhook
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Webhook deleted successfully
        '400':
          description: Bad request - Webhook associated with a subscription
    patch:
      summary: Update a webhook
      description: Update the details of a registered webhook.
      parameters:
        - name: webhookId
          in: path
          description: Unique identifier of the registered webhook
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WebhookUpdateRequest'
      responses:
        '200':
          description: Webhook updated successfully
components:
  schemas:
    WebhookRegistration:
      type: object
      properties:
        name:
          type: string
          description: Webhook name
        url:
          type: string
          description: Webhook URL
        retryCount:
          type: integer
          description: Number of retry attempts
        authHeader:
          type: string
          description: Authorization header value
        customHeaders:
          type: object
          description: Custom headers (Map)
        useCustomSSL:
          type: boolean
          description: Use custom SSL certificate
        customSSLCertificate:
          type: string
          format: binary
          description: Custom SSL certificate file (Upload file)
        tokenValidity:
          type: integer
          description: Token validity in seconds
    WebhookUpdateRequest:
      type: object
      properties:
        name:
          type: string
          description: Webhook name
        url:
          type: string
          description: Webhook URL
        retryCount:
          type: integer
          description: Number of retry attempts
        authHeader:
          type: string
          description: Authorization header value
        customHeaders:
          type: object
          description: Custom headers (Map)
        useCustomSSL:
          type: boolean
          description: Use custom SSL certificate
        customSSLCertificate:
          type: string
          format: binary
          description: Custom SSL certificate file (Upload file)
        tokenValidity:
          type: integer
          description: Token validity in seconds
    WebhookRegistrationResponse:
      type: object
      properties:
        webhookId:
          type: string
          description: Unique identifier for the registered webhook
    WebhookTestRequest:
      type: object
      properties:
        message:
          type: string
          description: Message to be sent for webhook testing
    WebhookTestResponse:
      type: object
      properties:
        echoedMessage:
          type: string
          description: Echoed message from the webhook test
    WebhookDataResponse:
      type: object
      properties:
        webhookId:
          type: string
          description: Unique identifier for the registered webhook
        name:
          type: string
          description: Webhook name
        url:
          type: string
          description: Webhook URL
        retryCount:
          type: integer
          description: Number of retry attempts
        authHeader:
          type: string
          description: Authorization header value
        customHeaders:
          type: object
          description: Custom headers (Map)
        useCustomSSL:
          type: boolean
          description: Use custom SSL certificate
        tokenValidity:
          type: integer
          description: Token validity in seconds
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/demo-arable/Webhooks/1.0.0
